### ISSUE TITLE
Distro / Repo Interdepency

### ISSUE THREAD

**Issue by biondogs** [mprov-ng/mprov_jobserver#70]
If i change a distro version, the repo must be updated first by checking the update repo in the os management > os repo > os repo name 

this is by design but we need to make sure people understand how it works

**Comment by jhujasonw** [comment]
Solving this could also be if a distro is updated, the repos that link to it should be as well?  But that would mean even config changes would update repos, which we don't want.  Not sure how best to document this though.   Or should we only call repo updates if the version changes?  Can we do that?

**Comment by jhujasonw** [comment]
closed in https://github.com/mprov-ng/mprov_jobserver/tree/6624eb93c162c00d4323802ff86bb87eaf016c4c and with https://github.com/mprov-ng/mprov_control_center/tree/af529140f48304b66168a81defefcf2f849b1a54
