### ISSUE TITLE
Alternatives incorrect in nads image

### ISSUE THREAD

**Issue by biondogs** [mprov-ng/mprov_jobserver#72]
[root@devmaster /]# alternatives
alternatives version 1.19.1 - Copyright (C) 2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License.

usage: alternatives --install <link> <name> <path> <priority>
                    [--initscript <service>]
                    [--family <family>]
                    [--slave <slave_link> <slave_name> <slave_path>]*
       alternatives --remove <name> <path>
       alternatives --auto <name>
       alternatives --config <name>
       alternatives --display <name>
       alternatives --set <name> <path>
       alternatives --list
       alternatives --remove-all <name>
       alternatives --add-slave <name> <path> <slave_link> <slave_name> <slave_path>
       alternatives --remove-slave <name> <path> <slave_name>

common options: --verbose --test --help --usage --version --keep-missing --keep-foreign
                --altdir <directory> --admindir <directory>
[root@devmaster /]# alternatives --list
libnssckbi.so.x86_64    auto    /usr/lib64/pkcs11/p11-kit-trust.so
python                  auto    /usr/libexec/no-python
cifs-idmap-plugin       auto    /usr/lib64/cifs-utils/cifs_idmap_sss.so
ld                      auto    /usr/bin/ld.bfd
python3                 auto    /usr/bin/python3.6
ofa_kernel_headers      auto    /usr/src/ofa_kernel/x86_64/4.18.0-477.10.1.el8_8.x86_64
libwbclient.so.0.15-64  auto    /usr/lib64/samba/wbclient/libwbclient.so.0.15
cufile.json             auto    /usr/local/cuda-11.7/gds/cufile.json
modules.sh              auto    /usr/share/lmod/lmod/init/profile
nsys                    manual  /opt/nvidia/nsight-systems/2023.2.3/target-linux-x64/nsys
nsys-ui                 manual  /opt/nvidia/nsight-systems/2023.2.3/host-linux-x64/nsys-ui
cuda                    auto    /usr/local/cuda-11.7
cuda-11                 auto    /usr/local/cuda-11.7
java                    auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre/bin/java
jre_openjdk             auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre
jre_1.8.0               auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre
jre_1.8.0_openjdk       auto    /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug
[root@devmaster /]# alternatives --
[root@devmaster /]# /usr/bin/python3
python3                  python3.6                python3.8                python3.8-x86_64-config
python3.11               python3.6m               python3.8-config
[root@devmaster /]# update-alternatives --install /usr/bin/python3.8 python
alternatives version 1.19.1 - Copyright (C) 2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License.

usage: alternatives --install <link> <name> <path> <priority>
                    [--initscript <service>]
                    [--family <family>]
                    [--slave <slave_link> <slave_name> <slave_path>]*
       alternatives --remove <name> <path>
       alternatives --auto <name>
       alternatives --config <name>
       alternatives --display <name>
       alternatives --set <name> <path>
       alternatives --list
       alternatives --remove-all <name>
       alternatives --add-slave <name> <path> <slave_link> <slave_name> <slave_path>
       alternatives --remove-slave <name> <path> <slave_name>

common options: --verbose --test --help --usage --version --keep-missing --keep-foreign
                --altdir <directory> --admindir <directory>
[root@devmaster /]# alternatives --list
libnssckbi.so.x86_64    auto    /usr/lib64/pkcs11/p11-kit-trust.so
python                  auto    /usr/libexec/no-python
cifs-idmap-plugin       auto    /usr/lib64/cifs-utils/cifs_idmap_sss.so
ld                      auto    /usr/bin/ld.bfd
python3                 auto    /usr/bin/python3.6
ofa_kernel_headers      auto    /usr/src/ofa_kernel/x86_64/4.18.0-477.10.1.el8_8.x86_64
libwbclient.so.0.15-64  auto    /usr/lib64/samba/wbclient/libwbclient.so.0.15
cufile.json             auto    /usr/local/cuda-11.7/gds/cufile.json
modules.sh              auto    /usr/share/lmod/lmod/init/profile
nsys                    manual  /opt/nvidia/nsight-systems/2023.2.3/target-linux-x64/nsys
nsys-ui                 manual  /opt/nvidia/nsight-systems/2023.2.3/host-linux-x64/nsys-ui
cuda                    auto    /usr/local/cuda-11.7
cuda-11                 auto    /usr/local/cuda-11.7
java                    auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre/bin/java
jre_openjdk             auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre
jre_1.8.0               auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre
jre_1.8.0_openjdk       auto    /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug
[root@devmaster /]# alternatives --config python

There are 4 programs which provide 'python'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/libexec/no-python
   2           /usr/bin/python3
   3           /usr/bin/python3.8
   4           /usr/bin/python3.11

Enter to keep the current selection[+], or type selection number: 3
[root@devmaster /]# alternatives --list
libnssckbi.so.x86_64    auto    /usr/lib64/pkcs11/p11-kit-trust.so
python                  manual  /usr/bin/python3.8
cifs-idmap-plugin       auto    /usr/lib64/cifs-utils/cifs_idmap_sss.so
ld                      auto    /usr/bin/ld.bfd
python3                 auto    /usr/bin/python3.6
ofa_kernel_headers      auto    /usr/src/ofa_kernel/x86_64/4.18.0-477.10.1.el8_8.x86_64
libwbclient.so.0.15-64  auto    /usr/lib64/samba/wbclient/libwbclient.so.0.15
cufile.json             auto    /usr/local/cuda-11.7/gds/cufile.json
modules.sh              auto    /usr/share/lmod/lmod/init/profile
nsys                    manual  /opt/nvidia/nsight-systems/2023.2.3/target-linux-x64/nsys
nsys-ui                 manual  /opt/nvidia/nsight-systems/2023.2.3/host-linux-x64/nsys-ui
cuda                    auto    /usr/local/cuda-11.7
cuda-11                 auto    /usr/local/cuda-11.7
java                    auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre/bin/java
jre_openjdk             auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre
jre_1.8.0               auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre
jre_1.8.0_openjdk       auto    /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug
[root@devmaster /]# alternatives --config python3

There are 3 programs which provide 'python3'.

  Selection    Command
-----------------------------------------------
   1           /usr/bin/python3.8
   2           /usr/bin/python3.11
*+ 3           /usr/bin/python3.6

Enter to keep the current selection[+], or type selection number: 1
[root@devmaster /]# alternatives --list
libnssckbi.so.x86_64    auto    /usr/lib64/pkcs11/p11-kit-trust.so
python                  manual  /usr/bin/python3.8
cifs-idmap-plugin       auto    /usr/lib64/cifs-utils/cifs_idmap_sss.so
ld                      auto    /usr/bin/ld.bfd
python3                 manual  /usr/bin/python3.8
ofa_kernel_headers      auto    /usr/src/ofa_kernel/x86_64/4.18.0-477.10.1.el8_8.x86_64
libwbclient.so.0.15-64  auto    /usr/lib64/samba/wbclient/libwbclient.so.0.15
cufile.json             auto    /usr/local/cuda-11.7/gds/cufile.json
modules.sh              auto    /usr/share/lmod/lmod/init/profile
nsys                    manual  /opt/nvidia/nsight-systems/2023.2.3/target-linux-x64/nsys
nsys-ui                 manual  /opt/nvidia/nsight-systems/2023.2.3/host-linux-x64/nsys-ui
cuda                    auto    /usr/local/cuda-11.7
cuda-11                 auto    /usr/local/cuda-11.7
java                    auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre/bin/java
jre_openjdk             auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre
jre_1.8.0               auto    /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug/jre
jre_1.8.0_openjdk       auto    /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64-slowdebug

**Comment by jhujasonw** [comment]
fixed in c4d64a116130ae6a34cc49f79dc227093f788371
